#PBS -N fgm-sfc-9-12

#PBS -l nodes=1:ppn=4,mem=16gb

#PBS -l walltime=48:00:00

#PBS -q tuc

#PBS -m abe -M something@example.com

#PBS -k oe

export PATH=/storage/tuclocal/ibalampanis/anaconda3/bin:$PATH

source /storage/tuclocal/ibalampanis/anaconda3/etc/profile.d/conda.sh

conda activate base

source /storage/tuclocal/ibalampanis/.bashrc

./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/sfc/9.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-sfc/exp9_iter1.txt
./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/sfc/10.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-sfc/exp10_iter1.txt
./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/sfc/11.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-sfc/exp11_iter1.txt
./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/sfc/12.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-sfc/exp12_iter1.txt