#PBS -N fgm-amazon-5-8

#PBS -l nodes=1:ppn=4,mem=16gb

#PBS -l walltime=48:00:00

#PBS -q tuc

#PBS -m abe -M something@example.com

#PBS -k oe

export PATH=/storage/tuclocal/ibalampanis/anaconda3/bin:$PATH

source /storage/tuclocal/ibalampanis/anaconda3/etc/profile.d/conda.sh

conda activate base

source /storage/tuclocal/ibalampanis/.bashrc

./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/amazon/5.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-amazon/exp5_iter1.txt
./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/amazon/6.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-amazon/exp6_iter1.txt
./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/amazon/7.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-amazon/exp7_iter1.txt
./FGMLearn /storage/tuclocal/ibalampanis/simulation/fgm/amazon/8.json >> /storage/tuclocal/ibalampanis/exp-results/fgm-amazon/exp8_iter1.txt