#PBS -N gm-amazon-13-16

#PBS -l nodes=1:ppn=4,mem=16gb

#PBS -l walltime=24:00:00

#PBS -q tuc

#PBS -m abe -M something@example.com

#PBS -k oe

export PATH=/storage/tuclocal/ibalampanis/anaconda3/bin:$PATH

source /storage/tuclocal/ibalampanis/anaconda3/etc/profile.d/conda.sh

conda activate base

source /storage/tuclocal/ibalampanis/.bashrc

./GMLearn /storage/tuclocal/ibalampanis/simulation/gm/amazon/13.json >> /storage/tuclocal/ibalampanis/exp-results/gm-amazon/exp13_iter1.txt
./GMLearn /storage/tuclocal/ibalampanis/simulation/gm/amazon/14.json >> /storage/tuclocal/ibalampanis/exp-results/gm-amazon/exp14_iter1.txt
./GMLearn /storage/tuclocal/ibalampanis/simulation/gm/amazon/15.json >> /storage/tuclocal/ibalampanis/exp-results/gm-amazon/exp15_iter1.txt
./GMLearn /storage/tuclocal/ibalampanis/simulation/gm/amazon/16.json >> /storage/tuclocal/ibalampanis/exp-results/gm-amazon/exp16_iter1.txt
